/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Ticket = IDL.Record({
  'pnr' : IDL.Text,
  'status' : IDL.Text,
  'passengerGender' : IDL.Text,
  'trainNumber' : IDL.Text,
  'trainDuration' : IDL.Text,
  'bookedAt' : IDL.Text,
  'coach' : IDL.Text,
  'seat' : IDL.Nat,
  'trainFrom' : IDL.Text,
  'trainName' : IDL.Text,
  'trainType' : IDL.Text,
  'passengerName' : IDL.Text,
  'trainTo' : IDL.Text,
  'travelDate' : IDL.Text,
  'travelClass' : IDL.Text,
  'passengerAge' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTicket' : IDL.Func([IDL.Text], [], []),
  'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTicketByPnr' : IDL.Func([IDL.Text], [IDL.Opt(Ticket)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTicket' : IDL.Func([Ticket], [], []),
  'submitMessage' : IDL.Func([ContactMessage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Ticket = IDL.Record({
    'pnr' : IDL.Text,
    'status' : IDL.Text,
    'passengerGender' : IDL.Text,
    'trainNumber' : IDL.Text,
    'trainDuration' : IDL.Text,
    'bookedAt' : IDL.Text,
    'coach' : IDL.Text,
    'seat' : IDL.Nat,
    'trainFrom' : IDL.Text,
    'trainName' : IDL.Text,
    'trainType' : IDL.Text,
    'passengerName' : IDL.Text,
    'trainTo' : IDL.Text,
    'travelDate' : IDL.Text,
    'travelClass' : IDL.Text,
    'passengerAge' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTicket' : IDL.Func([IDL.Text], [], []),
    'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTicketByPnr' : IDL.Func([IDL.Text], [IDL.Opt(Ticket)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTicket' : IDL.Func([Ticket], [], []),
    'submitMessage' : IDL.Func([ContactMessage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };