/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingStatus = IDL.Variant({
  'confirmed' : IDL.Null,
  'waiting' : IDL.Nat,
});
export const Passenger = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'coach' : IDL.Opt(IDL.Text),
  'seat' : IDL.Opt(IDL.Text),
  'gender' : IDL.Text,
});
export const TrainDetails = IDL.Record({
  'trainNumber' : IDL.Text,
  'journeyTo' : IDL.Text,
  'trainName' : IDL.Text,
  'trainType' : IDL.Text,
  'quota' : IDL.Text,
  'bookingTime' : IDL.Text,
  'journeyDate' : IDL.Text,
  'journeyFrom' : IDL.Text,
  'travelClass' : IDL.Text,
});
export const Booking = IDL.Record({
  'pnr' : IDL.Text,
  'status' : BookingStatus,
  'passengersCount' : IDL.Nat,
  'owner' : IDL.Principal,
  'quota' : IDL.Text,
  'passengers' : IDL.Vec(Passenger),
  'trainDetails' : TrainDetails,
  'travelDate' : IDL.Text,
  'bookingClass' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBooking' : IDL.Func([Booking], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getBookingsByPassengerName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByTrainNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsCountByClass' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getBookingsCountByQuota' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfirmedBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getTotalBookingsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaitingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingStatus = IDL.Variant({
    'confirmed' : IDL.Null,
    'waiting' : IDL.Nat,
  });
  const Passenger = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'coach' : IDL.Opt(IDL.Text),
    'seat' : IDL.Opt(IDL.Text),
    'gender' : IDL.Text,
  });
  const TrainDetails = IDL.Record({
    'trainNumber' : IDL.Text,
    'journeyTo' : IDL.Text,
    'trainName' : IDL.Text,
    'trainType' : IDL.Text,
    'quota' : IDL.Text,
    'bookingTime' : IDL.Text,
    'journeyDate' : IDL.Text,
    'journeyFrom' : IDL.Text,
    'travelClass' : IDL.Text,
  });
  const Booking = IDL.Record({
    'pnr' : IDL.Text,
    'status' : BookingStatus,
    'passengersCount' : IDL.Nat,
    'owner' : IDL.Principal,
    'quota' : IDL.Text,
    'passengers' : IDL.Vec(Passenger),
    'trainDetails' : TrainDetails,
    'travelDate' : IDL.Text,
    'bookingClass' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBooking' : IDL.Func([Booking], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getBookingsByPassengerName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByTrainNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsCountByClass' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getBookingsCountByQuota' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfirmedBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getTotalBookingsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaitingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };