/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'pnr' : string,
  'status' : BookingStatus,
  'passengersCount' : bigint,
  'owner' : Principal,
  'quota' : string,
  'passengers' : Array<Passenger>,
  'trainDetails' : TrainDetails,
  'travelDate' : string,
  'bookingClass' : string,
}
export type BookingStatus = { 'confirmed' : null } |
  { 'waiting' : bigint };
export interface Passenger {
  'age' : bigint,
  'name' : string,
  'coach' : [] | [string],
  'seat' : [] | [string],
  'gender' : string,
}
export interface TrainDetails {
  'trainNumber' : string,
  'journeyTo' : string,
  'trainName' : string,
  'trainType' : string,
  'quota' : string,
  'bookingTime' : string,
  'journeyDate' : string,
  'journeyFrom' : string,
  'travelClass' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBooking' : ActorMethod<[Booking], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[string], boolean>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[string], [] | [Booking]>,
  'getBookingsByDate' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByPassengerName' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByTrainNumber' : ActorMethod<[string], Array<Booking>>,
  'getBookingsCountByClass' : ActorMethod<[string], bigint>,
  'getBookingsCountByQuota' : ActorMethod<[string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfirmedBookings' : ActorMethod<[], Array<Booking>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getTotalBookingsCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaitingBookings' : ActorMethod<[], Array<Booking>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];