/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Ticket {
  'pnr' : string,
  'status' : string,
  'passengerGender' : string,
  'trainNumber' : string,
  'trainDuration' : string,
  'bookedAt' : string,
  'coach' : string,
  'seat' : bigint,
  'trainFrom' : string,
  'trainName' : string,
  'trainType' : string,
  'passengerName' : string,
  'trainTo' : string,
  'travelDate' : string,
  'travelClass' : string,
  'passengerAge' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTicket' : ActorMethod<[string], undefined>,
  'getAllTickets' : ActorMethod<[], Array<Ticket>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTicketByPnr' : ActorMethod<[string], [] | [Ticket]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMessages' : ActorMethod<[], Array<ContactMessage>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTicket' : ActorMethod<[Ticket], undefined>,
  'submitMessage' : ActorMethod<[ContactMessage], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];